//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIVIET_ROOTCOMMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIVIET_ROOTCOMMENT()
        {
            this.BAIVIET_CHILDCOMMENT = new HashSet<BAIVIET_CHILDCOMMENT>();
            this.BAIVIET_ROOTSCORE = new HashSet<BAIVIET_ROOTSCORE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MaBaiViet { get; set; }
        public Nullable<int> MaTK { get; set; }
        public string NoiDungBinhLuan { get; set; }
        public string NgayBinhLuan { get; set; }
        public Nullable<int> DiemDanhGiaBinhLuan { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET_CHILDCOMMENT> BAIVIET_CHILDCOMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET_ROOTSCORE> BAIVIET_ROOTSCORE { get; set; }
        public virtual BAIVIETDANHGIA BAIVIETDANHGIA { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
