//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIVIETDANHGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIVIETDANHGIA()
        {
            this.BAIVIET_ROOTCOMMENT = new HashSet<BAIVIET_ROOTCOMMENT>();
            this.BAIVIET_SCORE = new HashSet<BAIVIET_SCORE>();
        }
    
        public int MaBaiViet { get; set; }
        public Nullable<int> MaPhim { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<int> Score { get; set; }
        public string NoiDungNgan { get; set; }
        public string NoiDungBinhLuan { get; set; }
        public string NgayBinhLuan { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET_ROOTCOMMENT> BAIVIET_ROOTCOMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET_SCORE> BAIVIET_SCORE { get; set; }
        public virtual PHIM PHIM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
