//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int ID { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<int> MaDVD { get; set; }
        public string NameDVD { get; set; }
        public string Avata { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
