//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAODIENPHIM
    {
        public int ID { get; set; }
        public Nullable<int> MaPhim { get; set; }
        public Nullable<int> MaDienVien { get; set; }
    
        public virtual DIENVIEN DIENVIEN { get; set; }
        public virtual PHIM PHIM { get; set; }
    }
}
