//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIENVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIENVIEN()
        {
            this.ANHDIENVIENs = new HashSet<ANHDIENVIEN>();
            this.CHITIETDIENVIENNEWs = new HashSet<CHITIETDIENVIENNEW>();
            this.DAODIENPHIMs = new HashSet<DAODIENPHIM>();
            this.DIENVIENPHIMs = new HashSet<DIENVIENPHIM>();
            this.KICHBANPHIMs = new HashSet<KICHBANPHIM>();
        }
    
        public int MaDienVien { get; set; }
        public string NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string TieuSu { get; set; }
        public string AnhDaiDien { get; set; }
        public string TenDienVien { get; set; }
        public Nullable<bool> Star { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANHDIENVIEN> ANHDIENVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDIENVIENNEW> CHITIETDIENVIENNEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAODIENPHIM> DAODIENPHIMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIENVIENPHIM> DIENVIENPHIMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KICHBANPHIM> KICHBANPHIMs { get; set; }
    }
}
