//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVD()
        {
            this.BAGs = new HashSet<BAG>();
        }
    
        public int MaDVD { get; set; }
        public Nullable<int> MaPhim { get; set; }
        public Nullable<int> SoDia { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> SoLuongTrongKho { get; set; }
        public Nullable<bool> Status { get; set; }
        public string NgayCapNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAG> BAGs { get; set; }
        public virtual PHIM PHIM { get; set; }
    }
}
