//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NEW()
        {
            this.CHITIETDIENVIENNEWs = new HashSet<CHITIETDIENVIENNEW>();
            this.CHITIETPHIMNEWs = new HashSet<CHITIETPHIMNEW>();
            this.NewsScores = new HashSet<NewsScore>();
            this.RootCommentNews = new HashSet<RootCommentNew>();
        }
    
        public int MaNew { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<int> LoaiNew { get; set; }
        public string NoiDungNgan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public string NgayDang { get; set; }
        public string TuaNews { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDIENVIENNEW> CHITIETDIENVIENNEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIMNEW> CHITIETPHIMNEWs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsScore> NewsScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootCommentNew> RootCommentNews { get; set; }
    }
}
