//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERSEAT
    {
        public int ID { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<int> IDSuatChieu { get; set; }
        public string DanhSachGheDat { get; set; }
        public string QR { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string TapDoan { get; set; }
        public string DiaChiTapDoan { get; set; }
        public string TenKhach { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string NgayTaoHoaDon { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual SUATCHIEU SUATCHIEU { get; set; }
    }
}
