//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIM()
        {
            this.ANHPHIMs = new HashSet<ANHPHIM>();
            this.BAIVIETDANHGIAs = new HashSet<BAIVIETDANHGIA>();
            this.CHITIETPHIMNEWs = new HashSet<CHITIETPHIMNEW>();
            this.DAODIENPHIMs = new HashSet<DAODIENPHIM>();
            this.DIENVIENPHIMs = new HashSet<DIENVIENPHIM>();
            this.DVDs = new HashSet<DVD>();
            this.GENREPHIMs = new HashSet<GENREPHIM>();
            this.KICHBANPHIMs = new HashSet<KICHBANPHIM>();
            this.SCOREs = new HashSet<SCORE>();
            this.TVSHOWs = new HashSet<TVSHOW>();
            this.TVSHOWEPs = new HashSet<TVSHOWEP>();
        }
    
        public int MaPhim { get; set; }
        public string TenPhim { get; set; }
        public Nullable<int> IsTVShow { get; set; }
        public string TomTatNgan { get; set; }
        public string TomTat { get; set; }
        public string AnhDaiDien { get; set; }
        public string Trailer { get; set; }
        public Nullable<int> Studio { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Theaters { get; set; }
        public string OnDVD { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> LemonCatScore { get; set; }
        public Nullable<int> IMDBScore { get; set; }
        public Nullable<decimal> BoxOffice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANHPHIM> ANHPHIMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIETDANHGIA> BAIVIETDANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIMNEW> CHITIETPHIMNEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAODIENPHIM> DAODIENPHIMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIENVIENPHIM> DIENVIENPHIMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVD> DVDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENREPHIM> GENREPHIMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KICHBANPHIM> KICHBANPHIMs { get; set; }
        public virtual STUDIO STUDIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCORE> SCOREs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVSHOW> TVSHOWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVSHOWEP> TVSHOWEPs { get; set; }
    }
}
