//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RootCommentNew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RootCommentNew()
        {
            this.ChildCommentNews = new HashSet<ChildCommentNew>();
            this.RootNewScores = new HashSet<RootNewScore>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MaNew { get; set; }
        public Nullable<int> MaTK { get; set; }
        public string NoiDungBinhLuan { get; set; }
        public string NgayBinhLuan { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildCommentNew> ChildCommentNews { get; set; }
        public virtual NEW NEW { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootNewScore> RootNewScores { get; set; }
    }
}
