//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORE
    {
        public int ID { get; set; }
        public Nullable<int> MaPhim { get; set; }
        public Nullable<int> UserScore { get; set; }
        public Nullable<int> CountUser { get; set; }
        public Nullable<int> LemonCatScore { get; set; }
        public Nullable<int> CountLemonCat { get; set; }
        public Nullable<int> MetacriditScore { get; set; }
        public Nullable<int> IMDBScore { get; set; }
        public Nullable<int> TomatoesScore { get; set; }
    
        public virtual PHIM PHIM { get; set; }
    }
}
