//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.BAGs = new HashSet<BAG>();
            this.BAIVIET_CHILDCOMMENT = new HashSet<BAIVIET_CHILDCOMMENT>();
            this.BAIVIET_ROOTCOMMENT = new HashSet<BAIVIET_ROOTCOMMENT>();
            this.BAIVIET_ROOTSCORE = new HashSet<BAIVIET_ROOTSCORE>();
            this.BAIVIET_SCORE = new HashSet<BAIVIET_SCORE>();
            this.BAIVIETDANHGIAs = new HashSet<BAIVIETDANHGIA>();
            this.ChildCommentNews = new HashSet<ChildCommentNew>();
            this.NEWs = new HashSet<NEW>();
            this.NewsScores = new HashSet<NewsScore>();
            this.RootCommentNews = new HashSet<RootCommentNew>();
            this.RootNewScores = new HashSet<RootNewScore>();
            this.VIEWEDPRODUCTs = new HashSet<VIEWEDPRODUCT>();
        }
    
        public int MaTK { get; set; }
        public string TenTK { get; set; }
        public string MatKhau { get; set; }
        public string RealPass { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> ChucVu { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<bool> KichHoat { get; set; }
        public Nullable<int> Money { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAG> BAGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET_CHILDCOMMENT> BAIVIET_CHILDCOMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET_ROOTCOMMENT> BAIVIET_ROOTCOMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET_ROOTSCORE> BAIVIET_ROOTSCORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET_SCORE> BAIVIET_SCORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIETDANHGIA> BAIVIETDANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildCommentNew> ChildCommentNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEW> NEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsScore> NewsScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootCommentNew> RootCommentNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootNewScore> RootNewScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIEWEDPRODUCT> VIEWEDPRODUCTs { get; set; }
    }
}
