//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonCat.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEARDATA
    {
        public int ID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> TongMovie { get; set; }
        public Nullable<int> TongTV { get; set; }
        public Nullable<int> TongUser { get; set; }
        public Nullable<int> TongDVD { get; set; }
        public Nullable<int> TongVe { get; set; }
        public Nullable<int> DoanhThuBanDVD { get; set; }
        public Nullable<int> DoanhThuBanVe { get; set; }
        public Nullable<int> TongUserLoaiMot { get; set; }
        public Nullable<int> TongUserDacBiet { get; set; }
        public Nullable<int> TongReview { get; set; }
        public Nullable<int> TongNews { get; set; }
        public string MonthDisplay { get; set; }
        public string YearDisplay { get; set; }
    }
}
